name: Code Coverage

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Pytest and Upload Coverage
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Run Pytest
        run: poetry run pytest --cov-report xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          flags: unittests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
